name: CI

on:
  push:
    branches: [main, reboot_ci]
  pull_request:
    branches: [main, reboot_ci]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Combination matrix:
#
# Lua         | Number as    | Linux     | Windows    | MacOSX    |
#             | float/double |           |            |           |
# ------------|--------------|------------------------------------|
# LuaJit 2.0  | N.A.         |     X     |            |           |
# ------------|--------------|------------------------------------|
# Lua 5.1     | float        |           |            |           |
#             |--------------|-----------|------------|-----------|
#             | double       |    X      |            |           |
# ------------|--------------|------------------------------------|
# Lua 5.2     | float        |    X      |            |           |
#             |--------------|-----------|------------|-----------|
#             | double       |           |            |           |
# ------------|--------------|------------------------------------|
# Lua 5.3     | float        |           |     X      |           |
#             |--------------|-----------|------------|-----------|
#             | double       |           |            |           |
# ------------|--------------|------------------------------------|
# Lua 5.4     | float        |           |            |           |
#             |--------------|-----------|------------|-----------|
#             | double       |     X     |      X     |    X      |
# ------------|--------------|------------------------------------|
#
# Strategy:
# - newest version is tested on all platform, in default configuration (double)
# - Each of lua 5.2, lua 5.3, luajit 2.0 is tested only on one platforms
# - float is tested on two platform
jobs:
  lua:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            luaVersion: 5.1

          - os: ubuntu-latest
            luaVersion: 5.2
            luaCompileFlags: LUA_CFLAGS="-DLUA_NUMBER_FLOAT=1"

          - os: windows-latest
            luaVersion: 5.3
            luaCompileFlags: LUA_CFLAGS="-DLUA_NUMBER_FLOAT=1"

          - os: ubuntu-latest
            luaVersion: luajit-2.0

          # Run lua 5.4 on all platforms
          - os: ubuntu-latest
            luaVersion: 5.4

          - os: macos-latest
            luaVersion: 5.4

          - os: windows-latest
            luaVersion: 5.4
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup msvc dev cmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: setup lua
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: ${{ matrix.luaVersion }}
          luaCompileFlags: ${{ matrix.luaCompileFlags }}

      - name: show lua version
        run: lua -v

      - name: run luacheck
        run: luacheck .

      - name: run unit tests
        run: lua run_unit_tests.lua --shuffle
        
      - name: run functional tests
        run: lua run_functional_tests.lua 

      - name: setup luarocks
        uses: leafo/gh-actions-luarocks@v6

      - name: install luacheck
        run: luarocks install luacheck

      - name: code check
        run: luacheck example_with_luaunit.lua luaunit.lua run_unit_tests.lua run_functional_tests.lua test/


# 
#           PLATFORM: ${{ runner.os }}
#         run: |
#           source ci/setup_lua.sh
#           lua -v -lluacov run_unit_tests.lua --shuffle          
#           lua run_functional_tests.lua --coverage
#           luacheck example_with_luaunit.lua luaunit.lua run_unit_tests.lua run_functional_tests.lua test/
#           # luacov-coveralls -v --include %./luaunit.lua
# 